### PR TITLE
Embedded A Frame scene

### PR DESCRIPTION
**Pull request by HarmonyEarth**
The scene is now embedded according to the documentation: [Embedded A Frame](https://aframe.io/docs/1.4.0/components/embedded.html)

I brought in the ARjs library as an NPM package. It definitely isn't as straightforward as your original import on the index file since the NPM package is kind of in beta. So if you have trouble installing the package, just remove it and uncomment the original import.

### CODE REVIEW

**Comment by nathank000** [comment]
attempting to re-open

**Comment by nathank000** [comment]
now can I?

**Comment by nathank000** [comment]
for some reason I can not re-open?
any chance you can?

**Comment by nathank000** [comment]
image

**Comment by HarmonyEarth** [comment]
Hey my mistake, I deleted my fork on the 19th since I thought you didn't need it. I didn't know this would prevent the pull request from being able to be reopened.
I will create a new pull request shortly.

**Comment by HarmonyEarth** [comment]
[Link to New Pull Request](https://github.com/nathank000/R8_last/pull/2)

**Pull request closed without merging**
